core/urls.py
from django.conf.urls import url
from core import views
from django.views.decorators.cache import cache_page
from django.conf import settings
from .sitemaps import StaticCoreViewSitemap, PeopleDetailViewSitemap

app_name = 'core'

sitemaps = {
    'core_static': StaticCoreViewSitemap(),
    'core_people_detail': PeopleDetailViewSitemap(),
}

urlpatterns = [
    url(
        r'^people/$',
        views.PeoplePage.as_view(),
        name='people'),
    url(
        r'^people/(?P<user_id>[^/]+)$',
        views.PeopleDetailPage.as_view(),
        name='user'),
    url(
        r'^contributions/$',
        views.ContributionsPage.as_view(),
        name='contributions'),
    url(
        r'^archive/',
        cache_page(settings.FROSCH_CACHE_TIMEOUT)(views.RedirectToMostRecentArchivedConference.as_view()),
        name='archive'),
    url(
        r'^contact/$', views.Contact.as_view(), name='contact'),
]

frosch/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language
from django.conf import settings
from django.views.static import serve as static_serve
from django.contrib.sitemaps import views as sitemap_views
from core.views import SitemapLangIndex, RedirectToNextConference
from core.urls import sitemaps as core_sitemaps
from core.conference_urls import sitemaps as core_conference_sitemaps
from news.urls import sitemaps as news_sitemaps
from pages.urls import sitemaps as pages_sitemaps
from callforcontributions.urls import sitemaps as call_sitemaps
from callforcontributions.conference_urls import sitemaps as call_conference_sitemaps
from visitorregistration.urls import sitemaps as registration_sitemaps
from staffregistration.urls import sitemaps as staff_sitemaps
from django.views.decorators.cache import cache_page


sitemaps = {}
sitemaps.update(core_sitemaps)
sitemaps.update(core_conference_sitemaps)
sitemaps.update(news_sitemaps)
sitemaps.update(pages_sitemaps)
sitemaps.update(call_sitemaps)
sitemaps.update(call_conference_sitemaps)
sitemaps.update(registration_sitemaps)
sitemaps.update(staff_sitemaps)



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^lang/', set_language, name="set-lang"),
    url(r'^sitemap\.xml$', SitemapLangIndex.as_view(), name='sitemap_index'),
    url(r'^robots\.txt', include('robots.urls')),
]

conf_pref = settings.FROSCH_CONFERENCE_PREFIX #}|past-events/|archiv/)"

urlpatterns += i18n_patterns(
    url(r'', include('core.urls', namespace='core')),
    url(fr'^{conf_pref}', include('core.conference_urls', namespace='core_conference')),
    url(
        r'^next/.*$',
        cache_page(settings.FROSCH_CACHE_TIMEOUT)(RedirectToNextConference.as_view()),
        name='next_conference'),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/call/',
        include('callforcontributions.conference_urls', namespace='call')),
    url(r'', include('callforcontributions.urls', namespace='noconfcall')),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/registration/',
        include('visitorregistration.urls', namespace='visitorregistration')),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/staff/',
        include('staffregistration.urls', namespace='staff')),
    url(r'^accounts/', include('core.account_urls', namespace='accounts')),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    url(r'', include('news.urls', namespace='news')),
    url(r'', include('pages.urls', namespace='page')),
    url(r'^sitemap\.xml$', sitemap_views.sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^media/(?P<path>.*)$',
            static_serve, {'document_root': settings.MEDIA_ROOT}),
    ]

# set the error handlers to defaults to prevent other modules (e.g., suit) to overwrite these handlers
handler400 = 'django.views.defaults.bad_request'
handler403 = 'django.views.defaults.permission_denied'
handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'

news/urls.py
from django.conf.urls import  url
from .views import IndexView, ArticleView
from .feeds import NewsFeed
from .sitemaps import NewsIndexViewSitemap, NewsArticleViewSitemap

app_name = 'news'

sitemaps = {
    'news_static': NewsIndexViewSitemap(),
    'news_article': NewsArticleViewSitemap(),
}

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^news/page/(?P<page>[0-9]+)/$', IndexView.as_view(), name='index'),
    url(r'^news/article/(?P<slug>[^/]+)', ArticleView.as_view(), name='article-detail'),
    url(r'news/feed/', NewsFeed(), name='feed'),
]

news/models.py
from django.db import models
from django.utils import timezone
from filer.fields.image import FilerImageField
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=200)
    published = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=100)
    text = models.TextField()
    is_active = models.BooleanField(default=False)
    image = FilerImageField(blank=True, null=True, on_delete=models.SET_NULL)
    video = models.URLField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('news:article-detail', args=[str(self.slug)])

news/views.py
from .models import Article
from django.views.generic import ListView, DetailView
from core.view_utils import DetailViewTranslationURLProviderMixin, PreviousConferenceMixin


class IndexView(PreviousConferenceMixin, ListView):
    template_name = 'news/index.html'
    queryset = Article.objects.filter(is_active=True)
    ordering = '-published'
    paginate_by = 20
    context_object_name = 'articles'
    

class ArticleView(DetailViewTranslationURLProviderMixin, DetailView):
    model = Article
    queryset = Article.objects.filter(is_active=True)

news/templates/news/article.html
{% load markdown_deux_tags thumbnail video_embed %}


<article class="card mb-3">
    <h5 class="card-header article-header">{{ article.title }} <a href="{% url 'news:article-detail' article.slug %}">{{ article.published|date }}</a></h5>
    <div class="card-body">
	<div class="card-text">{{ article.text|markdown:"trusted" }}</div>
    </div>
    {% if article.image %}
    <img class="card-img-bottom" src="{% thumbnail article.image 1000x400 crop %}" alt="">
    {% endif %}
    {% if article.video %}
	{% video_embed article.video %}
    {% endif %}
</article>

news/templates/news/article_detail.html
{% extends "page-with-cards.html" %}
{% load i18n cache bootstrap4 thumbnail %}

{% block title %}{{ FROSCH_NAME }}{% endblock %}

{% if article.image %}
{% block og_image %}{% thumbnail article.image 1000x1000 %}{% endblock %}
{% endif %}

{% block jumbotron %}
{% include 'mixins/conference-jumbotrons.html' %}
{% endblock %}


{% block maincontent %}

<p><a href="{% url 'news:index' %}">&laquo; {% trans "Back to main page " %}</a></p>
{% include 'news/article.html' %}



{% endblock %}

news/templates/news/index.html
{% extends "page-with-cards.html" %}
{% load i18n bootstrap4 thumbnail staticfiles %}

{% block title %}{{ FROSCH_NAME }}{% endblock %}

{% block og_image %}{% with active_conferences.all|first as conference %}{% if conference.intro_image %}{% thumbnail conference.intro_image 1200x630 crop quality=95 %}{% else %}{% static 'images/piandmore.png' %}{% endif %}{% endwith %}{% endblock %}

{% block jumbotron %}
{% include 'mixins/conference-jumbotrons.html' %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
<link rel="alternate" type="application/rss+xml" title="News" href="{{ FROSCH_BASE_URL }}{% url 'news:feed' %}">
{% endblock %}


{% block maincontent %}

{% if is_paginated and page_obj.number > 1 %}
{% include './includes/paginator.html' %}
{% endif %}


{% for article in articles %}
{% include 'news/article.html' %}
{% endfor %}


{% if is_paginated %}
{% include './includes/paginator.html' %}
{% endif %}

{% endblock %}

{% block extracards %}
{% include 'cards/previous-conference.html' %}
{% include 'cards/search-contribution.html' %}
{% include 'cards/twitter.html' %}
{% include 'cards/youtube.html' %}
{% endblock %}