core/urls.py
from django.conf.urls import url
from core import views
from django.views.decorators.cache import cache_page
from django.conf import settings
from .sitemaps import StaticCoreViewSitemap, PeopleDetailViewSitemap

app_name = 'core'

sitemaps = {
    'core_static': StaticCoreViewSitemap(),
    'core_people_detail': PeopleDetailViewSitemap(),
}

urlpatterns = [
    url(
        r'^people/$',
        views.PeoplePage.as_view(),
        name='people'),
    url(
        r'^people/(?P<user_id>[^/]+)$',
        views.PeopleDetailPage.as_view(),
        name='user'),
    url(
        r'^contributions/$',
        views.ContributionsPage.as_view(),
        name='contributions'),
    url(
        r'^archive/',
        cache_page(settings.FROSCH_CACHE_TIMEOUT)(views.RedirectToMostRecentArchivedConference.as_view()),
        name='archive'),
    url(
        r'^contact/$', views.Contact.as_view(), name='contact'),
]

frosch/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language
from django.conf import settings
from django.views.static import serve as static_serve
from django.contrib.sitemaps import views as sitemap_views
from core.views import SitemapLangIndex, RedirectToNextConference
from core.urls import sitemaps as core_sitemaps
from core.conference_urls import sitemaps as core_conference_sitemaps
from news.urls import sitemaps as news_sitemaps
from pages.urls import sitemaps as pages_sitemaps
from callforcontributions.urls import sitemaps as call_sitemaps
from callforcontributions.conference_urls import sitemaps as call_conference_sitemaps
from visitorregistration.urls import sitemaps as registration_sitemaps
from staffregistration.urls import sitemaps as staff_sitemaps
from django.views.decorators.cache import cache_page


sitemaps = {}
sitemaps.update(core_sitemaps)
sitemaps.update(core_conference_sitemaps)
sitemaps.update(news_sitemaps)
sitemaps.update(pages_sitemaps)
sitemaps.update(call_sitemaps)
sitemaps.update(call_conference_sitemaps)
sitemaps.update(registration_sitemaps)
sitemaps.update(staff_sitemaps)



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^lang/', set_language, name="set-lang"),
    url(r'^sitemap\.xml$', SitemapLangIndex.as_view(), name='sitemap_index'),
    url(r'^robots\.txt', include('robots.urls')),
]

conf_pref = settings.FROSCH_CONFERENCE_PREFIX #}|past-events/|archiv/)"

urlpatterns += i18n_patterns(
    url(r'', include('core.urls', namespace='core')),
    url(fr'^{conf_pref}', include('core.conference_urls', namespace='core_conference')),
    url(
        r'^next/.*$',
        cache_page(settings.FROSCH_CACHE_TIMEOUT)(RedirectToNextConference.as_view()),
        name='next_conference'),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/call/',
        include('callforcontributions.conference_urls', namespace='call')),
    url(r'', include('callforcontributions.urls', namespace='noconfcall')),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/registration/',
        include('visitorregistration.urls', namespace='visitorregistration')),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/staff/',
        include('staffregistration.urls', namespace='staff')),
    url(r'^accounts/', include('core.account_urls', namespace='accounts')),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    url(r'', include('news.urls', namespace='news')),
    url(r'', include('pages.urls', namespace='page')),
    url(r'^sitemap\.xml$', sitemap_views.sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^media/(?P<path>.*)$',
            static_serve, {'document_root': settings.MEDIA_ROOT}),
    ]

# set the error handlers to defaults to prevent other modules (e.g., suit) to overwrite these handlers
handler400 = 'django.views.defaults.bad_request'
handler403 = 'django.views.defaults.permission_denied'
handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'

pages/urls.py
from pages import views
from django.conf.urls import url
from django.conf import settings
from .sitemaps import PageViewSitemap, ConferencePageViewSitemap

app_name = 'pages'

sitemaps = {
    'pages_page': PageViewSitemap(),
    'pages_conference_page': ConferencePageViewSitemap(),
}


urlpatterns = [
    url(
        r'^%s(?P<conference_id>[^/]+)/(?P<pagemount_slug>.+)/$' % settings.FROSCH_CONFERENCE_PREFIX, views.ConferencePage.as_view(), name='conference_page'),
    url(
        r'^(?P<pagemount_slug>.+)/$', views.Page.as_view(), name='page'),
]

core/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (login as auth_login, logout as do_logout,
                                 update_session_auth_hash)
from django.contrib.auth.models import Group
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.db.models import Q, Count, Min
from django.http import (Http404, HttpResponseRedirect,
                         JsonResponse)
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from django.template import RequestContext
from django.utils.http import is_safe_url, urlencode
from django.utils.translation import override, ugettext_lazy as _

from .forms import ContactForm
from .view_utils import ConferenceQuerysets
from active_login_required import active_login_required
from callforcontributions.models import Event, EventStatus
from core.view_utils import ConferenceScheduleView, ScheduleLayer
from core.forms import (UserChangeForm, UserCreationForm,
                        UserPasswordResetForm)
from core.models import (Conference, User, UserAvailability,
                         send_templated_mail_to_frosch_admins)
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, TemplateView, ListView, FormView
from .models import Room
from post_office import mail
from sponsormanager.view_utils import SponsorViewMixin
from core.models import Scheduleable
from django.views.decorators.http import condition



class ConferenceContextMixin():

    def get_conference(self):
        if not hasattr(self, 'conference'):
            self.conference = get_object_or_404(Conference, url_snippet=self.kwargs.get('conference_id'))
        return self.conference
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'conference': self.get_conference()
        })
        return context


def send_register_mail(request, user, redirect_to):
    url = (
        reverse(
            'accounts:unlock', args=[user.id, user.secret_token]
        ) + "?" + urlencode({
            'next': redirect_to
        })
    )
    user.send_templated_mail(request, 'core.register', {
        'unlock_url': request.build_absolute_uri(url),
    })

    
def get_public_schedule_view(conference, day):
    # Schedule view
    events = Event.objects.filter(
        conference=conference,
        version=Event.RELEASED,
        status__in=[EventStatus.CONFIRMED, EventStatus.UNCONFIRMED],
        day_id=day.id,
    ).order_by('day__start', 'start_datetime', 'room__sort_key', 'room__name')
    rooms = Room.objects.filter(
        event__in=events.filter(scheduled=Event.SS_DTR)
    ).distinct().order_by('sort_key', 'name')

    active_layer = ScheduleLayer(events)
    active_layer.template = 'core/mixins/schedule-public-event.html'

    view = ConferenceScheduleView(
        conference,
        conference.conferenceday_set.filter(id=day.id),
        rooms,
        active_layer,
        public_times=True,
    )
    events_notime = events.filter(scheduled=Event.SS_DR)
    return (day, view, events_notime)
    

def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('accounts:profile'))
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            send_register_mail(request, new_user, redirect_to)
            return HttpResponseRedirect(reverse('accounts:thanks'))
    else:
        form = UserCreationForm()

    return render(request, "registration/register.html", {
        'form': form,
        'next': redirect_to
    })


def thanks(request):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, "registration/thanks.html")


def login(request):
    if request.user.is_authenticated() and not request.user.is_active:
        send_register_mail(request, request.user, reverse('accounts:profile'))
        return HttpResponseRedirect(reverse('accounts:thanks'))
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('accounts:profile'))
    
    class CustomAuthenticationForm(AuthenticationForm):
        def __init__(self, *args, **kwargs):
            super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
            self.error_messages['invalid_login'] = _(
                "Your email address and password didn't match. "
                "Note that both fields may be case-sensitive.")
    return LoginView.as_view(request, authentication_form=CustomAuthenticationForm)


def logout(request):
    do_logout(request)
    return HttpResponseRedirect(resolve_url(settings.LOGIN_REDIRECT_URL))


def unlock(request, user_id, user_secret_token):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    if len(user_secret_token) == 0:
        raise Http404(_("Secret token not provided."))
    user = get_object_or_404(User, id=user_id, secret_token=user_secret_token)
    redirect_to = request.GET.get('next', '')
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if user.is_active:
        return HttpResponseRedirect(redirect_to)
    else:
        user.is_active = True
        user.save()
        # We now log the user in (for this one time only!)
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        auth_login(request, user)

        mail.send(
            template='core.notify-user-registration',
            recipients=[x[1] for x in settings.ADMINS],
            context=RequestContext(request, {
                'user': user,
                'FROSCH_NAME': settings.FROSCH_NAME,

            })
        )

        return render(request, "registration/unlocked.html", {
            'user': user,
            'next': redirect_to
        })

    
def reset_password(request, user_id=None, user_password_reset_token=None):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if request.method == 'POST' and request.POST.get('identifier', '') != '':
        users = User.objects.filter(Q(username=request.POST['identifier']) | Q(email=request.POST['identifier']))
        for u in users.all():  # there might be multiple users (same mail address for different users)
            u.generate_password_reset_token()
            u.save()
            reset_url = request.build_absolute_uri(reverse(
                'accounts:new-password', args=[u.id, u.password_reset_token]) + 
                                                   "?" + urlencode({'next': redirect_to}))
            u.send_templated_mail(request, 'core.reset-password', {
                    'reset_url': reset_url,
            })
        return render(request, "registration/reset-password.html", {
            'identifier': request.POST['identifier'],
            'results': users.count(),
            'next': redirect_to
        })
    return render(request, "registration/reset-password.html", {
        'next': redirect_to
    })


def new_password(request, user_id, user_password_reset_token):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    user = get_object_or_404(User, id=user_id, password_reset_token=user_password_reset_token)

    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if request.method == 'POST':
        form = UserPasswordResetForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user)
            user.is_active = True
            user.save()
            # We now log the user in (for this one time only!)
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            auth_login(request, user)
            return HttpResponseRedirect(redirect_to)
    else:
        form = UserPasswordResetForm(instance=user)
    return render(request, "registration/new-password.html", {
        'form': form,
        'next': redirect_to,
        'recovery_user': user
    })


@active_login_required
def profile(request):
    def get_instance(conference_day):
        return UserAvailability.objects.get_or_create(
            user=request.user,
            day=conference_day,
            defaults={
                'start': conference_day.start,
                'end': conference_day.end
            }
        )[0]

    if request.method == 'POST':
        form = UserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            if request.POST.get('password1', ''):
                update_session_auth_hash(request, request.user)
            messages.success(request, _("Changes saved."))
            return HttpResponseRedirect(resolve_url('accounts:profile'))
    else:
        form = UserChangeForm(instance=request.user)
    return render(request, 'registration/profile.html', {
        'form': form,
    })


class ConferenceDetail(ConferenceContextMixin, SponsorViewMixin, TemplateView):
    template_name = 'core/conference_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

core/templates/core/conference_base.html
{% extends "page-with-cards-left.html" %}
{% load staticfiles thumbnail leaflet_tags compress %}

{% block title %}{{ FROSCH_NAME }}{% endblock %}


{% block navbar %}
{% if conference in archived_conferences %}
{% with subnav="subnav/archive.html" %}
{{ block.super }}
{% endwith %}
{% else %}
{% with subnav="subnav/conference.html" %}
{{ block.super }}
{% endwith %}
{% endif %}
{% endblock %}


{% block og_image %}{% if conference.intro_.image %}{% thumbnail conference.intro_image 1000x1000 %}{% else %}{{ block.super }}{% endif %}{% endblock %}


{% block extrahead %}
{% compress js %}
{% leaflet_js %}
<script src="{% static 'awesome-markers/leaflet.awesome-markers.js' %}"></script>
<script src="{% static 'lightbox/ekko-lightbox.js' %}"></script>
<script src="{% static 'iscroll/iscroll.js' %}"></script>
{% endcompress %}
{% compress css %}
{% leaflet_css %}
<link href="{% static 'awesome-markers/leaflet.awesome-markers.css' %}" rel="stylesheet">
<link href="{% static 'lightbox/ekko-lightbox.css' %}" rel="stylesheet">
{% endcompress %}
{% endblock %}

{% block extrafooter %}
<script>
 $(document).on('click', '[data-toggle="lightbox"]', function(event) {
     event.preventDefault();
     $(this).ekkoLightbox({
     });
 });
</script>
{% endblock %}

core/templates/core/conference_base_fullwidth.html
{% extends "page-with-cards-left-fullwidth.html" %}
{% load staticfiles thumbnail leaflet_tags %}

{% block title %}{{ FROSCH_NAME }}{% endblock %}


{% block navbar %}
{% if conference in archived_conferences %}
{% with subnav="subnav/archive.html" %}
{{ block.super }}
{% endwith %}
{% else %}
{% with subnav="subnav/conference.html" %}
{{ block.super }}
{% endwith %}
{% endif %}
{% endblock %}


{% block og_image %}{% if conference.intro_.image %}{% thumbnail conference.intro_image 1000x1000 %}{% else %}{{ block.super }}{% endif %}{% endblock %}


{% block extrahead %}
{% leaflet_js %}
{% leaflet_css %}
<script src="{% static 'awesome-markers/leaflet.awesome-markers.js' %}"></script>
<link href="{% static 'awesome-markers/leaflet.awesome-markers.css' %}" rel="stylesheet">
{% endblock %}

core/templates/core/conference_base_no_cards.html
{% extends "page-without-cards.html" %}
{% load staticfiles thumbnail compress leaflet_tags %}

{% block title %}{{ FROSCH_NAME }}{% endblock %}


{% block navbar %}
{% if conference in archived_conferences %}
{% with subnav="subnav/archive.html" %}
{{ block.super }}
{% endwith %}
{% else %}
{% with subnav="subnav/conference.html" %}
{{ block.super }}
{% endwith %}
{% endif %}
{% endblock %}


{% block og_image %}{% if conference.intro_.image %}{% thumbnail conference.intro_image 1000x1000 %}{% else %}{{ block.super }}{% endif %}{% endblock %}


{% block extrahead %}
{% compress js %}
{% leaflet_js %}
<script src="{% static 'awesome-markers/leaflet.awesome-markers.js' %}"></script>
<script src="{% static 'lightbox/ekko-lightbox.js' %}"></script>
<script src="{% static 'iscroll/iscroll.js' %}"></script>
{% endcompress %}
{% compress css %}
{% leaflet_css %}
<link href="{% static 'awesome-markers/leaflet.awesome-markers.css' %}" rel="stylesheet">
<link href="{% static 'lightbox/ekko-lightbox.css' %}" rel="stylesheet">
{% endcompress %}
{% endblock %}

{% block extrafooter %}
<script>
 $(document).on('click', '[data-toggle="lightbox"]', function(event) {
     event.preventDefault();
     $(this).ekkoLightbox({
     });
 });
</script>
{% endblock %}

core/templates/core/conference_detail.html
{% extends "./conference_base_no_cards.html" %}

{% load l10n i18n staticfiles cache bootstrap4 thumbnail markdown_deux_tags %}

{% block title %}{{ conference.long_name }}{% endblock %}
{% block og_title %}{{ conference.long_name }}{% endblock %}

{% block og_image %}{% if conference.intro_image %}{% thumbnail conference.intro_image 1200x630 crop quality=95 %}{% else %}{% static 'images/piandmore.png' %}{% endif %}{% endblock %}

{% block maincontent %}

{% if user.is_staff %}
<div class="row">
    <div class="col-md-12" style="font-size: 85%;">
    <div class="btn-toolbar" role="toolbar">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">{{ conference.short_name }}</div>
            </div>
            {% if user.is_staff %}
            <a class="btn btn-secondary" href="{% url 'admin:core_conference_change' conference.id %}">edit</a>
            {% endif %}
            {% if conference.visitor_registration and conference.visitor_registration.is_active %}
            <div class="input-group-prepend">
                <div class="input-group-text">{{ conference.visitor_registration.booked_tickets }} ({{ conference.visitor_registration.booked_tickets_last_24h }} {% trans 'last 24 hours' %})</div>
            </div>
            {% endif %}
        </div>
        
    </div>
    <div class="btn-toolbar" role="toolbar">
        
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">Schedule: {{ conference.eventsettings.get_version }} ({{ conference.eventsettings.last_draft_released|date }})</div>
            </div>
            <a class="btn btn-secondary" href="{% url 'admin:versionable_callforcontributions.conferenceeventsettings_changes' conference.id %}">
                {% if conference.eventsettings.needs_release %}
                <i class="text-danger fas fa-exclamation-triangle" title="Changes detected - needs release!"></i>
                {% endif %}
                {% trans 'release' %}
            </a>
            <a class="btn btn-secondary" href="{% url 'admin:callforcontributions_event_changelist' %}?conference={{ conference.id }}">list</a>
            <a class="btn btn-secondary" href="{% url 'admin:schedule/events' conference.id %}">scheduler</a>
        </div>
        
    </div>
    <div class="btn-toolbar" role="toolbar">


        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">Jobs: {{ conference.conferencestaffsettings.get_version }} ({{ conference.conferencestaffsettings.last_draft_released|date }})</div>
            </div>
            <a class="btn btn-secondary" href="{% url 'admin:versionable_staffregistration.conferencestaffsettings_changes' conference.id %}">
                {% if conference.conferencestaffsettings.needs_release %}
                <i class="text-danger fas fa-exclamation-triangle" title="Changes detected - needs release!"></i>
                {% endif %}
                {% trans 'release' %}
            </a>
            <a class="btn btn-secondary" href="{% url 'admin:staffregistration_job_changelist' %}?conference={{ conference.id }}">list</a>
            <a class="btn btn-secondary" href="{% url 'admin:schedule/jobs' conference.id %}">scheduler</a>
        </div>

        
    </div>
    </div>
</div>
{% endif %}


<!-- Main Article -->        
<article class="card mb-3">
    {% include 'core/conference/intro_image.html' %}
    {% if sponsors and not conference in archived_conferences %}
    <div class="row">
        <div class="col-md-8">
            <div class="card-body">
                {% include 'core/conference/information.html' %}
            </div>
        </div>
        <div class="col-md-4">
            {% include 'core/cards/conference_sponsors.html' %}
        </div>
    </div>
    {% else %}
    <div class="card-body">
        {% include 'core/conference/information.html' %}
    </div>
    {% endif %}
    
    {% include 'core/conference/gallery.html' %}
    {% include 'core/conference/highlights.html' %}        
</article>

{% if conference  not in archived_conferences %}
<article class="card mb-3">
    {% include 'core/conference/venue.html' %}
</article>
{% endif %}

{% if conference.eventsettings.last_draft_released %}
<article class="card mb-3">
    {% include 'core/mixins/public-schedule-grid.html' %}
</article>
{% endif %}

<div class="modal" id="eventModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg modal-content" role="document">
    </div>
</div>

{% endblock %}

core/templates/core/conference_event_detail.html
{% extends "./conference_base.html" %}
{% load l10n i18n staticfiles cache bootstrap4 thumbnail markdown_deux_tags leaflet_tags geojson_tags  %}

{% block title %}{{ FROSCH_NAME }}{% endblock %}

{% block extracards %}
{% include 'core/cards/conference_quick_facts.html' with conference=event.conference %}
{% include 'cards/search-contribution.html' %}
{% endblock %}


{% block maincontent %}
<!-- Main Article -->
<p><a href="{% url 'core_conference:conference' event.conference.url_snippet %}">&laquo; {% trans "Back to schedule for " %}{{ event.conference.short_name }}</a></p>
<div class="mt-3">
  {% include 'core/event.html' with hideClose=True %}
</div>
{% endblock %}

core/templates/core/conference_page.html
{% extends "./conference_base.html" %}
{% load i18n bootstrap4 %}

{% block maincontent %}

{{ pagemount.page.content }}

{% endblock %}

core/templates/core/contact_form.html
{% load markdown_deux_tags bootstrap4 i18n %}
{{ contact_page_content|markdown:"trusted" }}
<form method="post" {% if modal %}id="contact-form"{% endif %}>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% if not modal %}
    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button> {% if imprint_page_slug %}<a href="{% url 'page:page' imprint_page_slug %}">{% trans 'Imprint' %}</a>{% endif %}
    {% endif %}
</form>

core/templates/core/contact_page.html
{% extends "page-without-cards.html" %}
{% load i18n bootstrap4 markdown_deux_tags %}

{% block title %}{{ FROSCH_NAME }}{% endblock %}


{% block maincontent %}

<div class="card">
    <h3 class="card-header bg-dark text-white">
	{% trans "Contact" %}
    </h3>
    <div class="card-body">
	{% include 'core/contact_form.html' with form=form %}
    </div>
</div>
    
{% endblock %}

core/templates/core/event.html
{% load i18n markdown_deux_tags video_embed %}

<article class="card event" id="event-{{event.stable_id}}">
    <h2 class="card-header">{% if not hideClose|default:False %}
        <i class="fas fa-times" style="float: right;" onclick="$('#eventModal').modal('hide');"></i>
        {% endif %}{{ event.title }}{% if event.subtitle %}<br><span class="invisible" hidden> — </span><small>{{ event.subtitle }}</small><br><small>{{ event.event_type.name }}{% if event.track %} ({% trans "Track" %} {{ event.track }}){% endif %}</small>{% endif %}
      
	{% if user.is_staff %}
        <a href="{% url 'admin:callforcontributions_event_change' event.stable_id %}" class="editlink">✎</a>
        {% endif %}
    </h2>
    <div class="card-body">
	{% if event.teaser_image %}
	<img src="data:image/png;base64,{{ event.get_teaser_image_as_base64 }}" class="eventimage" alt="">
	{% endif %}
	<p class="card-text text-muted">
	    {% if event.scheduled == event.SS_DTR %}
	    {{ event.start_datetime|time:"H:i" }}{% trans "h"%} &ndash; {{ event.end_datetime|time:"H:i" }}{% trans "h"%}, {{ event.room }}
	    {% elif event.scheduled == event.SS_DR %}
	    {% trans "Whole day in" %} {{ event.room}}
	    {% else %}
	    {{ event.start_datetime|time:"H:i" }}{% trans "h"%} &ndash; {{ event.end_datetime|time:"H:i" }}{% trans "h"%}
	    {% endif %}
	</p>
	<div class="card-text">
	    {{ event.description|markdown }}

	    {% if event.speaker.all|length and not event.hide_speakers %}
	    <p>{%trans "By" %} {% for s in event.speaker.all %}
		<a href="{% url 'core:user' s.id %}">{{ s.username }}</a>{% if s.affiliation %} ({{ s.affiliation }}){% endif %}{% if forloop.revcounter > 1 %}{% if forloop.revcounter > 2 %},{% else %} {% trans "and" %} {% endif %}{% endif %}
		{% endfor %}</p>
	    {% endif %}
            
	    {% if event.public_links.all or event.public_media.all %}
	    <h5>{% trans "More information"%}:</h5>
	    <ul>
		{% for link in event.public_links.all %}
		<li><a href="{{ link.link }}" target="_blank">{{ link.name }}</a></li>
		{% endfor %}
		{% for media in event.public_media.all %}
		<li><a href="{% url 'call:public-media' event.conference.url_snippet media.id %}" target="_blank">{% if media.name %}{{ media.name }}{% else %}Download{% endif %}</a>{% if media.name %} (Download){% endif %}</li>
		{% endfor %}
	    </ul>
	    {% endif %}
	    {% if event.video %}
	    {% video_embed event.video %}
	    {% endif %}

	</div>
    </div>
    <div class="card-footer">
      <a class="card-link" href="{% url 'core_conference:conference_public_event' event.conference.url_snippet event.stable_id %}" title="{% trans 'Permanent Link' %}"><i class="fas fa-external-link-alt"></i></a>
      <a class="card-link" href="https://twitter.com/intent/tweet?text={{ event.title|urlencode }}&via=piandmore&url={% url 'core_conference:conference_public_event' event.conference.url_snippet event.stable_id %}" title="{% trans 'Share on Twitter' %}"><i class="fab fa-twitter"></i></a>
    </div>
</article>

core/templates/core/page.html
{% extends "page-with-cards.html" %}
{% load i18n bootstrap4 markdown_deux_tags %}

{% block title %}{{ FROSCH_NAME }}{% endblock %}


{% block maincontent %}

<article class="card">
    <h3 class="card-header bg-dark text-white">
	{{ pagemount.page.title }}
    </h3>
    <div class="card-body">
	{{ pagemount.page.content|markdown:"trusted" }}
    </div>
</article>
    
{% endblock %}