callforcontributions/urls.py
from django.conf.urls import url

from callforcontributions import views
from active_login_required import active_login_required

app_name = 'callforcontributions'

sitemaps = {}

urlpatterns = [
    url(r'^myevents/$', active_login_required(views.MyEventList.as_view()), name='myeventlist'),
]

core/urls.py
from django.conf.urls import url
from core import views
from django.views.decorators.cache import cache_page
from django.conf import settings
from .sitemaps import StaticCoreViewSitemap, PeopleDetailViewSitemap

app_name = 'core'

sitemaps = {
    'core_static': StaticCoreViewSitemap(),
    'core_people_detail': PeopleDetailViewSitemap(),
}

urlpatterns = [
    url(
        r'^people/$',
        views.PeoplePage.as_view(),
        name='people'),
    url(
        r'^people/(?P<user_id>[^/]+)$',
        views.PeopleDetailPage.as_view(),
        name='user'),
    url(
        r'^contributions/$',
        views.ContributionsPage.as_view(),
        name='contributions'),
    url(
        r'^archive/',
        cache_page(settings.FROSCH_CACHE_TIMEOUT)(views.RedirectToMostRecentArchivedConference.as_view()),
        name='archive'),
    url(
        r'^contact/$', views.Contact.as_view(), name='contact'),
]

frosch/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language
from django.conf import settings
from django.views.static import serve as static_serve
from django.contrib.sitemaps import views as sitemap_views
from core.views import SitemapLangIndex, RedirectToNextConference
from core.urls import sitemaps as core_sitemaps
from core.conference_urls import sitemaps as core_conference_sitemaps
from news.urls import sitemaps as news_sitemaps
from pages.urls import sitemaps as pages_sitemaps
from callforcontributions.urls import sitemaps as call_sitemaps
from callforcontributions.conference_urls import sitemaps as call_conference_sitemaps
from visitorregistration.urls import sitemaps as registration_sitemaps
from staffregistration.urls import sitemaps as staff_sitemaps
from django.views.decorators.cache import cache_page


sitemaps = {}
sitemaps.update(core_sitemaps)
sitemaps.update(core_conference_sitemaps)
sitemaps.update(news_sitemaps)
sitemaps.update(pages_sitemaps)
sitemaps.update(call_sitemaps)
sitemaps.update(call_conference_sitemaps)
sitemaps.update(registration_sitemaps)
sitemaps.update(staff_sitemaps)



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^lang/', set_language, name="set-lang"),
    url(r'^sitemap\.xml$', SitemapLangIndex.as_view(), name='sitemap_index'),
    url(r'^robots\.txt', include('robots.urls')),
]

conf_pref = settings.FROSCH_CONFERENCE_PREFIX #}|past-events/|archiv/)"

urlpatterns += i18n_patterns(
    url(r'', include('core.urls', namespace='core')),
    url(fr'^{conf_pref}', include('core.conference_urls', namespace='core_conference')),
    url(
        r'^next/.*$',
        cache_page(settings.FROSCH_CACHE_TIMEOUT)(RedirectToNextConference.as_view()),
        name='next_conference'),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/call/',
        include('callforcontributions.conference_urls', namespace='call')),
    url(r'', include('callforcontributions.urls', namespace='noconfcall')),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/registration/',
        include('visitorregistration.urls', namespace='visitorregistration')),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/staff/',
        include('staffregistration.urls', namespace='staff')),
    url(r'^accounts/', include('core.account_urls', namespace='accounts')),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    url(r'', include('news.urls', namespace='news')),
    url(r'', include('pages.urls', namespace='page')),
    url(r'^sitemap\.xml$', sitemap_views.sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^media/(?P<path>.*)$',
            static_serve, {'document_root': settings.MEDIA_ROOT}),
    ]

# set the error handlers to defaults to prevent other modules (e.g., suit) to overwrite these handlers
handler400 = 'django.views.defaults.bad_request'
handler403 = 'django.views.defaults.permission_denied'
handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'

news/urls.py
from django.conf.urls import  url
from .views import IndexView, ArticleView
from .feeds import NewsFeed
from .sitemaps import NewsIndexViewSitemap, NewsArticleViewSitemap

app_name = 'news'

sitemaps = {
    'news_static': NewsIndexViewSitemap(),
    'news_article': NewsArticleViewSitemap(),
}

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^news/page/(?P<page>[0-9]+)/$', IndexView.as_view(), name='index'),
    url(r'^news/article/(?P<slug>[^/]+)', ArticleView.as_view(), name='article-detail'),
    url(r'news/feed/', NewsFeed(), name='feed'),
]

pages/urls.py
from pages import views
from django.conf.urls import url
from django.conf import settings
from .sitemaps import PageViewSitemap, ConferencePageViewSitemap

app_name = 'pages'

sitemaps = {
    'pages_page': PageViewSitemap(),
    'pages_conference_page': ConferencePageViewSitemap(),
}


urlpatterns = [
    url(
        r'^%s(?P<conference_id>[^/]+)/(?P<pagemount_slug>.+)/$' % settings.FROSCH_CONFERENCE_PREFIX, views.ConferencePage.as_view(), name='conference_page'),
    url(
        r'^(?P<pagemount_slug>.+)/$', views.Page.as_view(), name='page'),
]

core/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (login as auth_login, logout as do_logout,
                                 update_session_auth_hash)
from django.contrib.auth.models import Group
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.db.models import Q, Count, Min
from django.http import (Http404, HttpResponseRedirect,
                         JsonResponse)
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from django.template import RequestContext
from django.utils.http import is_safe_url, urlencode
from django.utils.translation import override, ugettext_lazy as _

from .forms import ContactForm
from .view_utils import ConferenceQuerysets
from active_login_required import active_login_required
from callforcontributions.models import Event, EventStatus
from core.view_utils import ConferenceScheduleView, ScheduleLayer
from core.forms import (UserChangeForm, UserCreationForm,
                        UserPasswordResetForm)
from core.models import (Conference, User, UserAvailability,
                         send_templated_mail_to_frosch_admins)
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, TemplateView, ListView, FormView
from .models import Room
from post_office import mail
from sponsormanager.view_utils import SponsorViewMixin
from core.models import Scheduleable
from django.views.decorators.http import condition



class ConferenceContextMixin():

    def get_conference(self):
        if not hasattr(self, 'conference'):
            self.conference = get_object_or_404(Conference, url_snippet=self.kwargs.get('conference_id'))
        return self.conference
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'conference': self.get_conference()
        })
        return context


def send_register_mail(request, user, redirect_to):
    url = (
        reverse(
            'accounts:unlock', args=[user.id, user.secret_token]
        ) + "?" + urlencode({
            'next': redirect_to
        })
    )
    user.send_templated_mail(request, 'core.register', {
        'unlock_url': request.build_absolute_uri(url),
    })

    
def get_public_schedule_view(conference, day):
    # Schedule view
    events = Event.objects.filter(
        conference=conference,
        version=Event.RELEASED,
        status__in=[EventStatus.CONFIRMED, EventStatus.UNCONFIRMED],
        day_id=day.id,
    ).order_by('day__start', 'start_datetime', 'room__sort_key', 'room__name')
    rooms = Room.objects.filter(
        event__in=events.filter(scheduled=Event.SS_DTR)
    ).distinct().order_by('sort_key', 'name')

    active_layer = ScheduleLayer(events)
    active_layer.template = 'core/mixins/schedule-public-event.html'

    view = ConferenceScheduleView(
        conference,
        conference.conferenceday_set.filter(id=day.id),
        rooms,
        active_layer,
        public_times=True,
    )
    events_notime = events.filter(scheduled=Event.SS_DR)
    return (day, view, events_notime)
    

def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('accounts:profile'))
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            send_register_mail(request, new_user, redirect_to)
            return HttpResponseRedirect(reverse('accounts:thanks'))
    else:
        form = UserCreationForm()

    return render(request, "registration/register.html", {
        'form': form,
        'next': redirect_to
    })


def thanks(request):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, "registration/thanks.html")


def login(request):
    if request.user.is_authenticated() and not request.user.is_active:
        send_register_mail(request, request.user, reverse('accounts:profile'))
        return HttpResponseRedirect(reverse('accounts:thanks'))
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('accounts:profile'))
    
    class CustomAuthenticationForm(AuthenticationForm):
        def __init__(self, *args, **kwargs):
            super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
            self.error_messages['invalid_login'] = _(
                "Your email address and password didn't match. "
                "Note that both fields may be case-sensitive.")
    return LoginView.as_view(request, authentication_form=CustomAuthenticationForm)


def logout(request):
    do_logout(request)
    return HttpResponseRedirect(resolve_url(settings.LOGIN_REDIRECT_URL))


def unlock(request, user_id, user_secret_token):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    if len(user_secret_token) == 0:
        raise Http404(_("Secret token not provided."))
    user = get_object_or_404(User, id=user_id, secret_token=user_secret_token)
    redirect_to = request.GET.get('next', '')
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if user.is_active:
        return HttpResponseRedirect(redirect_to)
    else:
        user.is_active = True
        user.save()
        # We now log the user in (for this one time only!)
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        auth_login(request, user)

        mail.send(
            template='core.notify-user-registration',
            recipients=[x[1] for x in settings.ADMINS],
            context=RequestContext(request, {
                'user': user,
                'FROSCH_NAME': settings.FROSCH_NAME,

            })
        )

        return render(request, "registration/unlocked.html", {
            'user': user,
            'next': redirect_to
        })

    
def reset_password(request, user_id=None, user_password_reset_token=None):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if request.method == 'POST' and request.POST.get('identifier', '') != '':
        users = User.objects.filter(Q(username=request.POST['identifier']) | Q(email=request.POST['identifier']))
        for u in users.all():  # there might be multiple users (same mail address for different users)
            u.generate_password_reset_token()
            u.save()
            reset_url = request.build_absolute_uri(reverse(
                'accounts:new-password', args=[u.id, u.password_reset_token]) + 
                                                   "?" + urlencode({'next': redirect_to}))
            u.send_templated_mail(request, 'core.reset-password', {
                    'reset_url': reset_url,
            })
        return render(request, "registration/reset-password.html", {
            'identifier': request.POST['identifier'],
            'results': users.count(),
            'next': redirect_to
        })
    return render(request, "registration/reset-password.html", {
        'next': redirect_to
    })


def new_password(request, user_id, user_password_reset_token):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    user = get_object_or_404(User, id=user_id, password_reset_token=user_password_reset_token)

    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if request.method == 'POST':
        form = UserPasswordResetForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user)
            user.is_active = True
            user.save()
            # We now log the user in (for this one time only!)
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            auth_login(request, user)
            return HttpResponseRedirect(redirect_to)
    else:
        form = UserPasswordResetForm(instance=user)
    return render(request, "registration/new-password.html", {
        'form': form,
        'next': redirect_to,
        'recovery_user': user
    })


@active_login_required
def profile(request):
    def get_instance(conference_day):
        return UserAvailability.objects.get_or_create(
            user=request.user,
            day=conference_day,
            defaults={
                'start': conference_day.start,
                'end': conference_day.end
            }
        )[0]

    if request.method == 'POST':
        form = UserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            if request.POST.get('password1', ''):
                update_session_auth_hash(request, request.user)
            messages.success(request, _("Changes saved."))
            return HttpResponseRedirect(resolve_url('accounts:profile'))
    else:
        form = UserChangeForm(instance=request.user)
    return render(request, 'registration/profile.html', {
        'form': form,
    })


class ConferenceDetail(ConferenceContextMixin, SponsorViewMixin, TemplateView):
    template_name = 'core/conference_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

core/templates/dialog.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="col-md-6 offset-md-3 pb-5">
    <div id="content">
        <div class="page-contentheader">
	    <h1>{% block dialog_title %}{% endblock %}</h1>
        </div>
        
        {% block dialog %}{% endblock %}
    </div>
</div>
{% endblock %}

core/templates/navbar.html
{% load i18n staticfiles bootstrap4 cache translate_url easy_thumbnails_tags %}

{% get_available_languages as LANGS %}
{% get_current_language as LANG %}

<nav id="topnav" class="navbar navbar-dark bg-dark navbar-expand-md {% if subnav %}has-subnav{% else %}mb-3{% endif %}" role="navigation">
    <a class="navbar-brand" href="{% url 'news:index' %}"><img src="{% static 'images/piandmore.png' %}" alt="Pi and More" style="height: 40px" > <span class="navbar-brand-text">Pi and More</span></a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"> 
	    {% for conference_nav in active_conferences %}
	    <li class="nav-item {% if conference == conference_nav %}active{% endif %}">
	        <a class="nav-link" href="{% url 'core_conference:conference' conference_nav.url_snippet %}">{{ conference_nav.short_name }}</a>
	    </li>
	    {% endfor %}
	    {% url 'core:people' as href_p %}
	    {% url 'core:contributions' as href_c %}

	    <li class="nav-item dropdown  {% if conference in archived_conferences or request.get_full_path == href_p or request.get_full_path == href_c %}active{% endif %}">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                {% trans 'Archive' %} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item {% if conference in archived_conferences %}active{% endif %}" href="{% url 'core:archive' %}">{% trans 'Events' %}</a>
                </li>
                <li>
                  <a class="dropdown-item {% if request.get_full_path == href_p %}active{% endif %}" href="{% url 'core:people' %}">{% trans 'People' %}</a>
                </li>
                <li>
                  <a class="dropdown-item {% if request.get_full_path == href_c %}active{% endif %}" href="{% url 'core:contributions' %}">{% trans 'Contributions' %}</a>
                </li>
              </ul>
	    </li>
	    {% for pagemount in pagemounts %}
	    <li class="nav-item {% if request.resolver_match.url_name == 'page' and request.resolver_match.namespaces.0 == 'page' and request.resolver_match.kwargs.pagemount_slug == pagemount.slug %}active{% endif %}">
	        <a class="nav-link" href="{% url 'page:page' pagemount.slug %}">{{ pagemount.title }}</a>
	    </li>
	    {% endfor %}
	</ul>
	<ul class="navbar-nav ml-auto">
	    {% if not user.is_authenticated or not user.is_active %}
	    <li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    {% trans "Log In" %}
		</a>
		<div class="dropdown-menu dropdown-menu-right dropdown-login-form">
                    
		    {% url 'accounts:reset-password' as reset_password_url %}
		    <form class="px-4 py-3" action="{% url 'accounts:login' %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="next" value="{{ request.path }}" />
			{% bootstrap_form login_form %}
			<button type="submit" class="btn btn-primary">{% trans 'login' %}</button>
		    </form>
		    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">TODO {% trans "Register as a visitor" %}</a>
		    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'accounts:register' %}?next={{ request.path }}">{% trans "Register as a contributor or volunteer" %}</a>
		    <div class="dropdown-divider"></div>
		    <a class="dropdown-item" href="{{ reset_password_url }}?next={{ request.path }}">{% trans "Forgot password?" %}</a>
		</div>
	    </li>
	    
	    {% else %}

	    <li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		  {% if not user.image %}
                  <i class="fas fa-user-circle" aria-hidden="true"></i>
                  {% else %}
                  <img src="{% thumbnail user.image 40x40 %}" class="userthumbnail">
                  {% endif %}&nbsp;&nbsp;{{ user }}
		</a>
		<div class="dropdown-menu">
		    {% if user.is_staff %}
		    <a class="dropdown-item" href="{% url 'admin:index' %}">{% trans "admin" %}</a>
		    <div class="dropdown-divider"></div>
		    {% endif %}
		    <a class="dropdown-item" href="{% url 'accounts:profile' %}">{% trans "edit profile" %}</a>
		    <a class="dropdown-item" href="{% url 'noconfcall:myeventlist' %}">{% trans "my contributions" %}</a>
		    <a class="dropdown-item" href="{% url 'accounts:logout' %}">{% trans "log out" %}</a>
		</div>
	    </li>
	    {% endif %}
	    <li class="nav-item">
		<a class="nav-link" href="{% url 'core:contact' %}" data-toggle="modal" data-target="#contact">{% trans "Contact" %}</a>
	    </li>
	    {% for code, name in LANGS %}
	    {% if code != LANG %}
	    {% get_language_info for code as l %}
	    <li class="nav-item">

		<form class="form-inline" method="post" action="{% url 'set-lang' %}">
		    {% csrf_token %}
		    <input type="hidden" name="language" value="{{ code }}" />
		    <input type="hidden" name="next" value="{% translate_url code %}" />
		    <button type="submit" class="btn btn-link nav-link" style="border:0;">
			{% static "" as static_base_url %}
		        <img style="margin-top:-3px;" src="{{ static_base_url }}/images/{{ code }}.svg" alt="" height="16">&nbsp;&nbsp;{{ l.name_local }}
		    </button>
		</form>
	    </li>
	    {% endif %}
	    {% endfor %}
	</ul>
    </div>
</nav>

{% if subnav %}
<nav id="subnav" class="navbar navbar-light bg-white navbar-expand-md mb-4" role="navigation">
    <div class="container">
	<div class="col-md-12">
            {% include subnav %}
	</div>
    </div>
</nav>
{% endif %}

<div id="contact" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="contactDialogLabel">{% trans "Contact" %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
		{% include 'core/contact_form.html' with form=contact_form modal=True %}
                
            </div>
            <div class="modal-footer">
                {% if imprint_page_slug %}<a href="{% url 'page:page' imprint_page_slug %}">{% trans 'Imprint' %}</a>{% endif %} <button id="contact-submit" type="button" class="btn btn-primary">{% trans "Submit" %}</button>
                <script>
                 $('#contact-submit').on('click', function() {
                     var data = $('#contact-form').serialize();
                     $.post("{% url 'core:contact' %}", data).done(function() {
                         alert('{% trans "Thanks, we will get back to you as soon as possible!" %}');
                         $('#contact-form textarea').val('');
                         $('#contact').modal('hide');
                     }).fail(function(e) {
                         if (e.status == 400) {
                             alert('{% trans "Please fill all form fields." %}');
                         } else {
                             alert('{% blocktrans with email=contact_default_email %}Error, cannot send message. Please send an email to {{ email }}.{% endblocktrans %}');
                         };
                     });
                 });
                </script>
            </div>
        </div>
    </div>

</div>

{% if conference in archived_conferences %}
{% if not request.resolver_match.url_name == 'conference' or not request.resolver_match.namespaces.0 == 'core_conference' %}
<div class="container">
    <div class="alert alert-warning col-md-12">
	{% trans 'This is an archived sub page.' %} <a href="{% url 'core_conference:conference' conference.url_snippet %}">{% blocktrans with conference_name=conference.short_name %}Please click here to learn more about {{ conference_name }}.{% endblocktrans %}</a>
    </div>
</div>
{% endif %}
{% endif %}

core/templates/page-with-cards-left-fullwidth.html
{% extends "base.html" %}
{% load i18n staticfiles %}

{% block content %}

{% block jumbotron %}{% endblock %}

<div class="container-full ml-3 mr-3">
    <div class="row">
	<aside class="col-md-3">
            <div class="container" >
                <img src="{% static 'images/piandmore.png' %}" alt="Pi and More" style="width: 100%;" class="my-3" >
            </div>
	    {% with hide_on_small_devices=True %}
            {% block extracards %}
            {% endblock %}
	    {% block cards %}
            {% include 'cards/what-is-pi-and-more.html' %}
            {% include 'cards/newsletter.html' %}
	    {% endblock %}
	    {% endwith %}
	</aside>
	<div class="col-md-9">
	    {% block maincontent %}{% endblock %}
	</div>
    </div>
</div>
{% endblock %}

core/templates/page-with-cards-left.html
{% extends "base.html" %}
{% load i18n staticfiles %}

{% block content %}

{% block jumbotron %}{% endblock %}

<div class="container">
    <div class="row">
	<aside class="col-md-4">
            <div class="container" >
                <img src="{% static 'images/piandmore.png' %}" alt="Pi and More" style="width: 100%;" class="my-3" >
            </div>
	    {% with hide_on_small_devices=True %}
            {% block extracards %}
            {% endblock %}
	    {% block cards %}
            {% include 'cards/what-is-pi-and-more.html' %}
            {% include 'cards/newsletter.html' %}
	    {% endblock %}
	    {% endwith %}
	</aside>
	<div class="col-md-8">
	    {% block maincontent %}{% endblock %}
	</div>
    </div>
</div>
{% endblock %}

core/templates/page-with-cards.html
{% extends "base.html" %}
{% load i18n staticfiles %}

{% block content %}

{% block jumbotron %}{% endblock %}

<div class="container">
    <div class="row">
	<div class="col-md-8">
	    {% block maincontent %}{% endblock %}
	</div>
	<aside class="col-md-4">
            <div class="container" >
                <img src="{% static 'images/piandmore.png' %}" alt="Pi and More" style="width: 100%;" class="my-3" >
            </div>
            {% block extracards %}
            {% endblock %}
	    {% block cards %}
            {% include 'cards/what-is-pi-and-more.html' %}
            {% include 'cards/newsletter.html' %}
	    {% include 'cards/partners.html' %}
	    {% endblock %}
	</aside>
    </div>
</div>
{% endblock %}

core/templates/page-without-cards.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% block jumbotron %}{% endblock %}

<div class="container">
    <div class="row">
	<div class="col-md-12">
	    {% block maincontent %}{% endblock %}
	</div>
    </div>
</div>
{% endblock %}