core/urls.py
from django.conf.urls import url
from core import views
from django.views.decorators.cache import cache_page
from django.conf import settings
from .sitemaps import StaticCoreViewSitemap, PeopleDetailViewSitemap

app_name = 'core'

sitemaps = {
    'core_static': StaticCoreViewSitemap(),
    'core_people_detail': PeopleDetailViewSitemap(),
}

urlpatterns = [
    url(
        r'^people/$',
        views.PeoplePage.as_view(),
        name='people'),
    url(
        r'^people/(?P<user_id>[^/]+)$',
        views.PeopleDetailPage.as_view(),
        name='user'),
    url(
        r'^contributions/$',
        views.ContributionsPage.as_view(),
        name='contributions'),
    url(
        r'^archive/',
        cache_page(settings.FROSCH_CACHE_TIMEOUT)(views.RedirectToMostRecentArchivedConference.as_view()),
        name='archive'),
    url(
        r'^contact/$', views.Contact.as_view(), name='contact'),
]

frosch/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language
from django.conf import settings
from django.views.static import serve as static_serve
from django.contrib.sitemaps import views as sitemap_views
from core.views import SitemapLangIndex, RedirectToNextConference
from core.urls import sitemaps as core_sitemaps
from core.conference_urls import sitemaps as core_conference_sitemaps
from news.urls import sitemaps as news_sitemaps
from pages.urls import sitemaps as pages_sitemaps
from callforcontributions.urls import sitemaps as call_sitemaps
from callforcontributions.conference_urls import sitemaps as call_conference_sitemaps
from visitorregistration.urls import sitemaps as registration_sitemaps
from staffregistration.urls import sitemaps as staff_sitemaps
from django.views.decorators.cache import cache_page


sitemaps = {}
sitemaps.update(core_sitemaps)
sitemaps.update(core_conference_sitemaps)
sitemaps.update(news_sitemaps)
sitemaps.update(pages_sitemaps)
sitemaps.update(call_sitemaps)
sitemaps.update(call_conference_sitemaps)
sitemaps.update(registration_sitemaps)
sitemaps.update(staff_sitemaps)



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^lang/', set_language, name="set-lang"),
    url(r'^sitemap\.xml$', SitemapLangIndex.as_view(), name='sitemap_index'),
    url(r'^robots\.txt', include('robots.urls')),
]

conf_pref = settings.FROSCH_CONFERENCE_PREFIX #}|past-events/|archiv/)"

urlpatterns += i18n_patterns(
    url(r'', include('core.urls', namespace='core')),
    url(fr'^{conf_pref}', include('core.conference_urls', namespace='core_conference')),
    url(
        r'^next/.*$',
        cache_page(settings.FROSCH_CACHE_TIMEOUT)(RedirectToNextConference.as_view()),
        name='next_conference'),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/call/',
        include('callforcontributions.conference_urls', namespace='call')),
    url(r'', include('callforcontributions.urls', namespace='noconfcall')),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/registration/',
        include('visitorregistration.urls', namespace='visitorregistration')),
    url(fr'^{conf_pref}(?P<conference_id>[^/]+)/staff/',
        include('staffregistration.urls', namespace='staff')),
    url(r'^accounts/', include('core.account_urls', namespace='accounts')),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    url(r'', include('news.urls', namespace='news')),
    url(r'', include('pages.urls', namespace='page')),
    url(r'^sitemap\.xml$', sitemap_views.sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^media/(?P<path>.*)$',
            static_serve, {'document_root': settings.MEDIA_ROOT}),
    ]

# set the error handlers to defaults to prevent other modules (e.g., suit) to overwrite these handlers
handler400 = 'django.views.defaults.bad_request'
handler403 = 'django.views.defaults.permission_denied'
handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'

news/urls.py
from django.conf.urls import  url
from .views import IndexView, ArticleView
from .feeds import NewsFeed
from .sitemaps import NewsIndexViewSitemap, NewsArticleViewSitemap

app_name = 'news'

sitemaps = {
    'news_static': NewsIndexViewSitemap(),
    'news_article': NewsArticleViewSitemap(),
}

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^news/page/(?P<page>[0-9]+)/$', IndexView.as_view(), name='index'),
    url(r'^news/article/(?P<slug>[^/]+)', ArticleView.as_view(), name='article-detail'),
    url(r'news/feed/', NewsFeed(), name='feed'),
]

visitorregistration/urls.py
from django.conf.urls import url
from visitorregistration import views
from .sitemaps import VisitorregistrationStartViewSitemap

app_name = 'visitorregistration'

sitemaps = {
    'visitorregistration_start': VisitorregistrationStartViewSitemap(),
}

urlpatterns = [
    url(r'^$', views.StartView.as_view(), name='start'),
    url(r'^create$', views.CreateView.as_view(), name='create'),
    url(r'^edit/(?P<booking_id>[^/]+)$', views.EditView.as_view(), name='edit'),
    url(r'^show/(?P<booking_id>[^/]+)$', views.ShowView.as_view(), name='show'),
    url(r'^show/(?P<booking_id>[^/]+)/(?P<token>[^/]+)$', views.ShowWithTokenView.as_view(), name='show_with_token'),
    url(r'^request_confirmation_email/(?P<booking_id>[^/]+)$', views.RequestConfirmationEmailView.as_view(), name='request_confirmation_email'),
    url(r'^confirm_tickets/(?P<booking_id>[^/]+)$', views.ConfirmTicketsView.as_view(), name='confirm_tickets'),
    url(r'^request_email/$', views.RequestBookingTokens.as_view(), name='request_email'),
    url(r'^capacity$', views.RemainingCapacityView.as_view(), name='capacity'),
]

core/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (login as auth_login, logout as do_logout,
                                 update_session_auth_hash)
from django.contrib.auth.models import Group
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.db.models import Q, Count, Min
from django.http import (Http404, HttpResponseRedirect,
                         JsonResponse)
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from django.template import RequestContext
from django.utils.http import is_safe_url, urlencode
from django.utils.translation import override, ugettext_lazy as _

from .forms import ContactForm
from .view_utils import ConferenceQuerysets
from active_login_required import active_login_required
from callforcontributions.models import Event, EventStatus
from core.view_utils import ConferenceScheduleView, ScheduleLayer
from core.forms import (UserChangeForm, UserCreationForm,
                        UserPasswordResetForm)
from core.models import (Conference, User, UserAvailability,
                         send_templated_mail_to_frosch_admins)
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, TemplateView, ListView, FormView
from .models import Room
from post_office import mail
from sponsormanager.view_utils import SponsorViewMixin
from core.models import Scheduleable
from django.views.decorators.http import condition



class ConferenceContextMixin():

    def get_conference(self):
        if not hasattr(self, 'conference'):
            self.conference = get_object_or_404(Conference, url_snippet=self.kwargs.get('conference_id'))
        return self.conference
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'conference': self.get_conference()
        })
        return context


def send_register_mail(request, user, redirect_to):
    url = (
        reverse(
            'accounts:unlock', args=[user.id, user.secret_token]
        ) + "?" + urlencode({
            'next': redirect_to
        })
    )
    user.send_templated_mail(request, 'core.register', {
        'unlock_url': request.build_absolute_uri(url),
    })

    
def get_public_schedule_view(conference, day):
    # Schedule view
    events = Event.objects.filter(
        conference=conference,
        version=Event.RELEASED,
        status__in=[EventStatus.CONFIRMED, EventStatus.UNCONFIRMED],
        day_id=day.id,
    ).order_by('day__start', 'start_datetime', 'room__sort_key', 'room__name')
    rooms = Room.objects.filter(
        event__in=events.filter(scheduled=Event.SS_DTR)
    ).distinct().order_by('sort_key', 'name')

    active_layer = ScheduleLayer(events)
    active_layer.template = 'core/mixins/schedule-public-event.html'

    view = ConferenceScheduleView(
        conference,
        conference.conferenceday_set.filter(id=day.id),
        rooms,
        active_layer,
        public_times=True,
    )
    events_notime = events.filter(scheduled=Event.SS_DR)
    return (day, view, events_notime)
    

def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('accounts:profile'))
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            send_register_mail(request, new_user, redirect_to)
            return HttpResponseRedirect(reverse('accounts:thanks'))
    else:
        form = UserCreationForm()

    return render(request, "registration/register.html", {
        'form': form,
        'next': redirect_to
    })


def thanks(request):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, "registration/thanks.html")


def login(request):
    if request.user.is_authenticated() and not request.user.is_active:
        send_register_mail(request, request.user, reverse('accounts:profile'))
        return HttpResponseRedirect(reverse('accounts:thanks'))
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('accounts:profile'))
    
    class CustomAuthenticationForm(AuthenticationForm):
        def __init__(self, *args, **kwargs):
            super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
            self.error_messages['invalid_login'] = _(
                "Your email address and password didn't match. "
                "Note that both fields may be case-sensitive.")
    return LoginView.as_view(request, authentication_form=CustomAuthenticationForm)


def logout(request):
    do_logout(request)
    return HttpResponseRedirect(resolve_url(settings.LOGIN_REDIRECT_URL))


def unlock(request, user_id, user_secret_token):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    if len(user_secret_token) == 0:
        raise Http404(_("Secret token not provided."))
    user = get_object_or_404(User, id=user_id, secret_token=user_secret_token)
    redirect_to = request.GET.get('next', '')
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if user.is_active:
        return HttpResponseRedirect(redirect_to)
    else:
        user.is_active = True
        user.save()
        # We now log the user in (for this one time only!)
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        auth_login(request, user)

        mail.send(
            template='core.notify-user-registration',
            recipients=[x[1] for x in settings.ADMINS],
            context=RequestContext(request, {
                'user': user,
                'FROSCH_NAME': settings.FROSCH_NAME,

            })
        )

        return render(request, "registration/unlocked.html", {
            'user': user,
            'next': redirect_to
        })

    
def reset_password(request, user_id=None, user_password_reset_token=None):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if request.method == 'POST' and request.POST.get('identifier', '') != '':
        users = User.objects.filter(Q(username=request.POST['identifier']) | Q(email=request.POST['identifier']))
        for u in users.all():  # there might be multiple users (same mail address for different users)
            u.generate_password_reset_token()
            u.save()
            reset_url = request.build_absolute_uri(reverse(
                'accounts:new-password', args=[u.id, u.password_reset_token]) + 
                                                   "?" + urlencode({'next': redirect_to}))
            u.send_templated_mail(request, 'core.reset-password', {
                    'reset_url': reset_url,
            })
        return render(request, "registration/reset-password.html", {
            'identifier': request.POST['identifier'],
            'results': users.count(),
            'next': redirect_to
        })
    return render(request, "registration/reset-password.html", {
        'next': redirect_to
    })


def new_password(request, user_id, user_password_reset_token):
    if request.user.is_authenticated() and request.user.is_active:
        return HttpResponseRedirect(reverse('accounts:profile'))
    user = get_object_or_404(User, id=user_id, password_reset_token=user_password_reset_token)

    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if not is_safe_url(url=redirect_to, host=request.get_host()):
        redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

    if request.method == 'POST':
        form = UserPasswordResetForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user)
            user.is_active = True
            user.save()
            # We now log the user in (for this one time only!)
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            auth_login(request, user)
            return HttpResponseRedirect(redirect_to)
    else:
        form = UserPasswordResetForm(instance=user)
    return render(request, "registration/new-password.html", {
        'form': form,
        'next': redirect_to,
        'recovery_user': user
    })


@active_login_required
def profile(request):
    def get_instance(conference_day):
        return UserAvailability.objects.get_or_create(
            user=request.user,
            day=conference_day,
            defaults={
                'start': conference_day.start,
                'end': conference_day.end
            }
        )[0]

    if request.method == 'POST':
        form = UserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            if request.POST.get('password1', ''):
                update_session_auth_hash(request, request.user)
            messages.success(request, _("Changes saved."))
            return HttpResponseRedirect(resolve_url('accounts:profile'))
    else:
        form = UserChangeForm(instance=request.user)
    return render(request, 'registration/profile.html', {
        'form': form,
    })


class ConferenceDetail(ConferenceContextMixin, SponsorViewMixin, TemplateView):
    template_name = 'core/conference_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

core/templates/core/cards/conference_quick_facts.html
{% load i18n %}

<h1>{{ conference.short_name }}
    {% if user.is_staff %}
    <a href="{% url 'admin:core_conference_change' conference.id %}" class="editlink">✎</a>
    {% endif %}
</h1>
<div class="text-muted mb-3">
    {{ conference.venue }}
    {% if conference in archived_conferences %}<br>
    {{ conference.public_start|date }}
    {% endif %}
</div>
{% if not conference in archived_conferences %}
<div class="card mb-3">
    <h5 class="card-header">{% trans 'Quick Facts' %}</h5>
    <div class="card-body">
	<p class="card-text">
            <b>{% trans "Start" %}: </b> {{ conference.public_start }}<br>
            <b>{% trans "End" %}: </b> {{ conference.public_end }}
            {% if not conference.eventsettings.last_draft_released %}
            <br><b>({% trans "preliminary" %})</b>
            {% endif %}
        </p>

        {% if conference.visitor_registration and conference.visitor_registration.is_active %}
	<a class="btn btn-primary btn-sm mb-1" href="{% url 'visitorregistration:start' conference.url_snippet %}">{% trans "Register now (it's free!)" %}</a>
	{% endif %}
	{% if conference.eventsettings and conference.eventsettings.is_public %}
	<a class="btn btn-primary btn-sm mb-1" href="{% url 'call:index' conference.url_snippet %}">{% trans 'Submit your contribution' %}</a>
	{% endif %}
	{% if conference.conferencestaffsettings and conference.conferencestaffsettings.is_public %}
	<a class="btn btn-primary btn-sm mb-1" href="{% url 'staff:index' conference.url_snippet %}">{% trans 'Become a volunteer' %}</a>
	{% endif %}
        
        
    </div>
</div>

{% endif %}

core/templates/core/cards/conference_schedule_download.html
{% load qrcode i18n %}

<!-- download -->

<div class="card mb-3">
    <h5 class="card-header"><i class="fas fa-mobile-alt"></i> {% trans 'View on Mobile' %}</h5>
    <div class="card-body">

	<button class="btn btn-primary mb-1" type="button" data-toggle="collapse" data-target="#collapseDownload" aria-expanded="false" aria-controls="collapseExample">
	    {% trans "See instructions (Android)" %}
	</button>

	<div class="collapse" id="collapseDownload">
	    <div class="text-center">
		{{ "https://play.google.com/store/apps/details?id=net.gaast.giggity"|qrcode }}
	    </div>
	    <h5 class="card-title" >{% trans "Step 1: Install Giggity" %}</h5>
	    <p class="card-text">
		{% blocktrans %}Scan or click the QR code above to install the app <emph>Giggity</emph> by Wilmer van der Gaast which provides schedules for several open source community conferences.{% endblocktrans %}
	    </p>
	    <div class="text-center">
		{{ pentabarf_url|qrcode }}
	    </div>
	    <h5 class="card-title" >{% trans "Step 2: Load XML file" %}</h5>
	    <p class="card-text">
		{% blocktrans with confname=conference.short_name %}(If the schedule for
		{{ confname }} is not already
		shown in Giggity.) Scan the QR code above
		using Giggity to download and view the
		schedule.{% endblocktrans %}
	    </p>
	</div>
	<style>
	    #collapseDownload img {
	    margin-left: auto;
	    margin-right: auto;
	    }
	</style>
    </div>
</div>

core/templates/core/cards/conference_sponsors.html
{% load i18n thumbnail %}

{% if sponsors %}
<div class="card mb-3">
    <!-- <h5 class="card-header">{% trans 'Our Sponsors for ' %}{{ conference.short_name }}</h5> -->
    <div class="card-body">
	
	<div id="sponsors" style="display: grid; grid-template-columns: repeat({{ FROSCH_SPONSOR_GRID_GRANULARITY|add:1 }}, 1fr); grid-template-rows: 1fr;" >
	    {% for s in sponsors %}
	    {% ifchanged %}
	    <h4 class="card-title text-center mt-3" style="grid-column: 1/span {{FROSCH_SPONSOR_GRID_GRANULARITY}}">{{ s.sponsor.level.name }}</h4>
	    {% endifchanged %}
	    <a href="{{ s.sponsor.link }}" target="_blank" style="grid-column: {{ s.start }}/span {{ s.span }};" alt="{{ s.sponsor.name }}{% trans " supports " %}{{ conference.short_name }}" class="mt-3" >
		<img src="{% thumbnail s.sponsor.image 800x800 %}" alt="{{ s.sponsor.name }}" style=" width: 100%; height: auto;">
	    </a>
	    {% endfor %}
	</div>
    </div>
    
</div>
{% endif %}